### ISSUE TITLE
Is that possible to use shinyAce to edit an existing txt file with code

### ISSUE THREAD

**Issue by alexoor** [trestletech/shinyAce#23]
It looks like a predefined text string is always used in all examples. I wonder if there is a way to open a text file, edit and save. Then eval(parse()) for execution the code from the file. 

In utils package, we can use vi() to call a editor. However, it is not voked above Shiny page. Instead, it goes into R studio.

I am looking for a solution to edit text file directly in Shiny. 

Thanks,
Alex

**Comment by trestletech** [comment]
Sure. You could use something like `readLines` to read a file into a String which gets provided to ShinyAce, then use `writeLines` to update the file every time the reactive value changes.

**Comment by alexoor** [comment]
Yeap, I have tried that way, it works perfectly. Thank you so much for building such a nice tool and answering my question.
