### ISSUE TITLE
new version on CRAN ?

### ISSUE THREAD

**Issue by vnijs** [trestletech/shinyAce#26]
Do you have a timeline for when the new version will be on CRAN?

Thanks!!

**Comment by mostly-harmless** [comment]
bump

**Comment by mostly-harmless** [comment]
Sorry to keep bugging you but ... could you push the current version of shinyAce to CRAN?

**Comment by sjmgarnier** [comment]
I support @vnijs request to push the latest version (0.2.1) of shinyAce to CRAN. It's the last package missing for me to be able to submit my [`editR`](https://github.com/swarm-lab/editR) package to CRAN. 

Thanks for your hard work.

**Comment by vnijs** [comment]
Bump

**Comment by trestletech** [comment]
Sorry to be non-responsive. I had gone through a prolonged battle getting a package on CRAN recently and didn't have the emotional energy to do it again. 

I sat down to take a look at this tonight and found that we now have a couple of issues in `R CMD check` that would need to be resolved before we can get this on CRAN. 

If someone's able to submit a PR, I'll do my best to review that in a timely manner and get this on CRAN. If someone's interested in helping with maintenance of this package, reach out to me.

**Comment by vnijs** [comment]
Thanks for the update Jeff. It is unfortunate that CRAN can be such a drain. Below the _highlights_ from R CMD check. There are 5 issues (see comments below). There is not much I can help with on 1-4 but I'm happy to work on 5 and submit a pull-request. Let me know.

1. Can the non-ASCII letter be removed?
2. Is size likely to be an issue for CRAN for a package like this? Is it an option to focus on a subset of programming languages etc. to support for the CRAN package?
3. Not sure what the issue is with the MIT license. I haven't used this license before.
4. No idea what "win32consoleCompletion" is. I don't use windows
5. Update documentation. 

```r
* checking DESCRIPTION meta-information ... OK
Warning in .write_description(db, ldpath) :
  Unknown encoding with non-ASCII data: converting to ASCII

* checking installed package size ... NOTE
  installed size is  9.9Mb
  sub-directories of 1Mb or more:
    www   9.7Mb

* checking DESCRIPTION meta-information ... NOTE
License components which are templates and need '+ file LICENSE':
  MIT
* checking top-level files ... NOTE
File
  LICENSE
is not mentioned in the DESCRIPTION file.

* checking dependencies in R code ... NOTE
Unexported object imported by a ':::' call: ‘utils:::.win32consoleCompletion’
  See the note in ?`:::` about the use of this operator.

* checking Rd \usage sections ... WARNING
Undocumented arguments in documentation object 'aceEditor'
  ‘vimKeyBinding’ ‘showLineNumbers’ ‘highlightActiveLine’

Undocumented arguments in documentation object 'updateAceEditor'
  ‘border’

Functions with \usage entries need to have the appropriate \alias
entries, and all their arguments documented.
The \usage entries must correspond to syntactically valid R code.
See chapter ‘Writing R documentation files’ in the ‘Writing R
Extensions’ manual.

Status: 1 WARNING, 4 NOTEs
```

**Comment by saurfang** [comment]
The `utils:::.win32consoleCompletion` is used for autocompletion.  

The is documented in `?rcompgen` (A Completion Generator for R). In the **Unexported API** section, it mentions

> There are several unexported functions in the package. Of these, a few are special because they provide the API through which other mechanisms can make use of the facilities provided by this package (they are unexported because they are not meant to be called directly by users).
...
The `.win32consoleCompletion` is similar in spirit, but is more geared towards the Windows GUI (or rather, any front-end that has no completion facilities of its own).

Thus I feel the use of this unexported function is justified as `shinyAce` provides an embedded R front-end on the web.

**Comment by sjmgarnier** [comment]
I might have some time in the next few weeks to work on this. I'll submit a PR once it's done. 

> Can the non-ASCII letter be removed? 

The problem is with the use of accented letter in the DESCRIPTION. Replacing the accented letter with non-accented ones solves the problem. 

> Is size likely to be an issue for CRAN for a package like this? Is it an option to focus on a subset of programming languages etc. to support for the CRAN package?

It's twice the size of the version of the package on CRAN. I don't think it'll be a big problem, but it'll most likely require to talk to a CRAN maintainer after the submission.

> Not sure what the issue is with the MIT license. I haven't used this license before.

It's an easy fix. The MIT license is a template license (see here: https://www.r-project.org/Licenses/MIT). The license field should read "License: MIT + file LICENSE" instead of "License: MIT", and the LICENSE file should only contain the following two lines:

```
YEAR: 2013

COPYRIGHT HOLDER: Jeff Allen
```

> No idea what "win32consoleCompletion" is. I don't use windows

This is our biggest issue, and one that might not be easy to solve. The problem here is the use of the ::: operator to access the .win32consoleCompletion function in the package utils. Using the ::: operator to access a masked function of another package is not recommended. Ideally @trestletech should talk to the maintainer of utils and try to convince this person to expose the function to make shinyAce CRAN compliant. If the maintainer of utils refuses to expose the function, then @trestletech will have to make the case of using ::: here with the CRAN maintainers. 

> Update documentation.

I'll try working on this as soon as possible. It shouldn't be too difficult to complete the documentation for the few missing items.

**Comment by vnijs** [comment]
Awesome!

**Comment by vnijs** [comment]
Any updates? Thanks

**Comment by trestletech** [comment]
sorry.

> The maintainer of this package has been sent an email to confirm the submission. After their confirmation the package will be passed to CRAN for review.


Fingers crossed!

**Comment by trestletech** [comment]
Huzzah! https://cran.rstudio.com/web/packages/shinyAce/index.html

Should trickle to other mirrors and have binaries built within 24 hours. 

I think I am out of the business of submitting to CRAN now, though. Even with all this work it still took a couple of rounds to get things the way they like them. Happy to take on another owner of this project who's interested in furthering development and future CRAN submissions, though.

**Comment by vnijs** [comment]
Thanks Jeff!!!

**Comment by vnijs** [comment]
@trestletech `shinyAce` is a fantastic tool and is central to an app I have been working on for some time (https://github.com/radiant-rstats). I have made a few updates to the `shinyAce`, including updating the version of ace, that I would love to get on CRAN. Given your message "I think I am out of the business of submitting to CRAN now ... Happy to take on another owner of this project who's interested in furthering development and future CRAN submissions, though." I'm wondering how I can best help to make that happen. 

See updates at https://github.com/vnijs/shinyAce

**Comment by trestletech** [comment]
Hi @vnijs. Your changes look good and I'd love to transfer control to you. Can you shoot me an email (see `maintainer("shinyAce")`) and we can figure out the logistics?

Thanks!
