### ISSUE TITLE
bug - tab key press represented by spaces

### ISSUE THREAD

**Issue by DesmondCampbell** [trestletech/shinyAce#27]
I’m using shinyAce as an editable text area.
The problem is with the tab character.
I preloaded the shinyAce textarea with a file’s contents.
In this file, the tab character delineates name value pairs etc
E.g. Alpha\t0.5
ShinyAce renders such text correctly and reflects it back to server.R correctly

However when I want to add another name value pair, pressing the tab key when I want a tab character, I get spaces reflected to the server.R instead of a tab character.
e.g. Beta    0.5

I can circumvent this bug by copy and pasting from a pre-existing tab character in the text area, e.g. from the Alpha\t0.5 above
Then the new name value pair works, e.g. is
Beta\t0.5

Do you need any more info?
Otherwise a great library.

Here is my sessionInfo()

> print( sessionInfo())
> R version 3.0.2 (2013-09-25)
> Platform: x86_64-w64-mingw32/x64 (64-bit)

locale:
[1] LC_COLLATE=English_United Kingdom.1252  LC_CTYPE=English_United Kingdom.1252    LC_MONETARY=English_United Kingdom.1252 LC_NUMERIC=C  
[5] LC_TIME=English_United Kingdom.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] shinyAce_0.2.1  kinship2_1.6.1  quadprog_1.5-5  Matrix_1.0-14   lattice_0.20-29 shinysky_0.1.2  plyr_1.8.1      RJSONIO_1.3-0   shiny_0.10.2.2  devtools_1.7.0 

loaded via a namespace (and not attached):
[1] bitops_1.0-6    digest_0.6.4    grid_3.0.2      htmltools_0.2.6 httpuv_1.3.2    httr_0.6.1      mime_0.2        R6_2.0.1        Rcpp_0.11.3     RCurl_1.95-4.5  stringr_0.6.2  
[12] tools_3.0.2     xtable_1.7-4   

Regards
Desmond

**Comment by DesmondCampbell** [comment]
For my shiny application I want the shinyAce editor to use hard (as opposed to soft) tabbing.

I see that the ace editor supports toggling of soft v hard tabs configurable with 
  To use soft tabs: editor.getSession().setUseSoftTabs(true);
(from - https://github.com/ajaxorg/ace/wiki/Embedding-API)

I also see that shinyAce has a function jsQuote().
Perhaps I could use this to set the editor to hard tabs.
I grepped the shinyAce/examples for uses of jsQuote() but found none.

So my question is how can I configure my shinyAce inplementation to use hard tabbing?

regards
Desmond

**Comment by vnijs** [comment]
@DesmondCampbell The current version on Github has options to set `tabSize`, (not) use `softTabs`, and (not) `showInvisibles`.  See `?shinyAce::aceEditor` for more information after installing using `devtools::install_github("trestletech/shinyAce")`

**Comment by vnijs** [comment]
See `inst/examples/01-basic` on GitHub for an example where you can change the different settings you are interested in
