### ISSUE TITLE
build error in DESCRIPTION

### ISSUE THREAD

**Issue by vnijs** [trestletech/shinyAce#28]
The description file is causing build errors. It also has non-ASCII data which will likely be a problem for CRAN

Build errors fixed by replacing ',' with ')' at the end of Authors

**Comment by trestletech** [comment]
Thanks. 3217e8ed3f2444f8c8077d9af2ac9cae9d513baf

**Comment by vnijs** [comment]
Thanks for the quick response. The package now builds but still throws a Non-ascii warning on build-check (and 4 notes)
