### ISSUE TITLE
Time delay in reactive input reflecting editor contents

### ISSUE THREAD

**Issue by vixr** [trestletech/shinyAce#31]
In the current version, I've noticed there's a time delay in the editor contents.

I have an actionButton that triggers an evaluation of input$myAce where myAce is the identity of the shinyAce widget.

I've noticed that if I wait a while after editing before pressing the actionButton, input$myAce evaluates correctly to the current contents of the editor. If I press the actionButton too quickly after editing, the contents of input$myAce does not reflect the current contents of the editor and instead reflects the contents from roughly ~5-10 seconds earlier.

**Comment by TomasHovorka** [comment]
I observe the same. Very annoying. Any workarounds known? thanks

**Comment by vnijs** [comment]
If this is still an issue, try setting `debounce` to a different value when you call `shinyAce`. The default is `1000` milliseconds. Re-open the issue if needed
