### ISSUE TITLE
Can shinyAce be integrated with rstudio-server?

### ISSUE THREAD

**Issue by krdeepakio** [trestletech/shinyAce#32]
Can this be integrated with rstudio server? Or, can we preload with some variables so that they show up in autocomplete?

**Comment by vnijs** [comment]
Rstudio uses the [Ace editor](https://ace.c9.io). See the [autocomplete](https://trestletech.shinyapps.io/shinyAce6/) example if that is what you are looking for. The code for this example is [here](https://github.com/trestletech/shinyAce/tree/master/inst/examples/06-autocomplete)
