### ISSUE TITLE
Autocompletion: R code completition not called when Ctrl-Space is pressed twice

### ISSUE THREAD

**Issue by skranz** [trestletech/shinyAce#41]
Hi,

thanks @saurfang for adding the code completion ability. I would like to propose a small improvement. Currently, R based code completion like the rlangCompleter is not called when the user presses Ctrl-Space twice with the same line. That is because shiny does not call the observer as the value of the shiny input for code completion has not change.
To fix this I have proposed a pull request that simple adds a random nonce in the call to `Shiny.onInputChange('shinyAce_' + inputId + '_hint', {` 
in the  rlangCompleter.

**Comment by skranz** [comment]
I tested it and it works fine in my examples and in the provided autcomplete example

https://github.com/trestletech/shinyAce/tree/master/inst/examples/06-autocomplete

**Comment by trestletech** [comment]
Closed by #42
