### ISSUE TITLE
Request: add placeholder argument

### ISSUE THREAD

**Issue by VMJim** [trestletech/shinyAce#47]
A nice feature would be a `placeholder` argument just like `textInput(placeholder = "type some code here", ...)`. 

Give it a thought :)

Jim

**Comment by vnijs** [comment]
[This SO answer](https://stackoverflow.com/questions/26695708/how-can-i-add-placeholder-text-when-the-editor-is-empty) suggests it is possible. Happy to look at a PR

**Comment by vnijs** [comment]
@VMJim I added an option to specify a placeholder when the shinyAce editor is empty based on this SO answer: https://stackoverflow.com/a/26700324/1974918

You can test it out by running the code below and clicking on the "Clear text" button or by simply removing the text in the editor manually. 

```
install.packages("devtools")
devtools::install_github("trestletech/shinyAce")
shiny::runApp(system.file("examples/01-basic", package="shinyAce"))
```

This seems to work nicely in several themes BUT not all of them. In, for example, "tomorrow" the placeholder text is not visible, even though it is shown in the page source. Any suggestions for a fix are very welcome!

The relevant JS code is linked below.

https://github.com/trestletech/shinyAce/blob/master/inst/www/shinyAce.js#L257-L277
cc @saurfang @detule @GregorDeCillia

**Comment by vnijs** [comment]
Placeholder now works as expected for all themes when the shinyAce editor is empty based on this SO answer: https://stackoverflow.com/a/26700324/1974918

You can test it out by running the code below and clicking on the "Clear text" button or by simply removing the text in the editor manually.

Unless any new issues pop up I plan to push this release to CRAN towards the end of this week.

```
install.packages("devtools")
devtools::install_github("trestletech/shinyAce")
shiny::runApp(system.file("examples/01-basic", package="shinyAce"))
```
