### ISSUE TITLE
autoCompleteList in aceEditor can not work

### ISSUE THREAD

**Issue by Ping2016** [trestletech/shinyAce#48]
```
library(shiny)
library(shinyAce)

shinyApp(
    ui = basicPage(
      aceEditor("mySmartEditor", "plot(wt ~ mpg, data=mtcars)", mode="r",
                autoComplete="live",
                autoCompleteList=list(mtcars=colnames(mtcars))), # can not work
      aceEditor("mySmartEditor2", "plot(wt ~ mpg, data=mtcars)", mode="r",
                autoComplete="live",
                autoCompleteList=list(mtcars=colnames(mtcars)))        
    ), # can anto complete
    
    server = function(session, input, output) {

      observe({
        comps <- list(mtcars = colnames(mtcars), airquality = colnames(airquality))
        updateAceEditor(session, "mySmartEditor2", autoCompleteList = comps)
      })
      
    }
)
```

Many thanks!

**Comment by vnijs** [comment]
What exactly doesn't work as you expect @Ping2016?

**Comment by vnijs** [comment]
Any ideas @saurfang?

**Comment by saurfang** [comment]
Yep, I can replicate the bug. Some commits broke the feature and completion list is not passed correctly into the HTML. @vnijs did you take over this repo here or does the development goes onto your fork instead?

**Comment by vnijs** [comment]
Thanks for checking @saurfang! I agreed with @trestletech to take over maintenance so updates can be submitted to CRAN.  Development of `shinyAce` will stay on https://github.com/trestletech/shinyAce. Any chance you could provide a PR for this issue?
