### ISSUE TITLE
aceAutocomplete not working when invoked within module

### ISSUE THREAD

**Issue by GregorDeCillia** [trestletech/shinyAce#49]
I read about [some previous](https://github.com/trestletech/shinyAce/issues/34) bug with shiny modules and I am afraid I found another one. When I call `aceAutocomplete` within a shiny module, autoComplete does not get enabled. Interestingly enough, everything works if I call `aceAutocomplete ` in the global server - even if the targeted input id is part of a module. Here is a minimal example. 

```
Editor <- function(input, output, session){
  ns = session$ns
  shinyAce::aceAutocomplete(ns("editor"))
  shinyAce::aceAutocomplete("editor")
}

EditorUI <- function(id){
  ns = NS(id)
  shinyAce::aceEditor(
    ns("editor"),
    "default",
    autoComplete = "live"
  )
}

my_id = "editor_id"
#my_id = NULL

shinyApp(
  EditorUI(my_id),
  function(input, output, session){
    callModule(Editor, my_id)
    #shinyAce::aceAutocomplete(NS(my_id, "editor"))
  }
)
```

If either of the commented lines get removed, autocomplete is working properly. In the first case, the module basically writes its outputs in the main `session` since `NS(NULL)` is the identity function. In the second case, `aceAutocomplete` gets invoked with the same id but a different session argument.

I found that passing session to the module as a parameter fixes the problem, but I really don't like this approach, since my modules are nested.

```
domain <- session
callModule(Editor, my_id, domain)  # use domain in aceAutocomplete 
```

**Comment by vnijs** [comment]
I don't use modules much and there is a pretty major new release of Shiny coming up. If the update to Shiny doesn't address your issue perhaps you could provide a PR for `shinyAce`?

**Comment by GregorDeCillia** [comment]
Thanks for your reply. I just tried my example above with the newest version of shiny to no avail.

My guess is that the namespaces are not working properly since there is some `id` of the form

    shinyAce_editorId_hint

responsible for the completions. However, shiny modules only allow suffixes for `id`s, no prefixes. I'll take a look and try to submit a PR.

**Comment by vnijs** [comment]
@GregorDeCillia Could you check if the current version on GitHub (0.3.01) works as expect in your setting? Thanks for your help!

**Comment by GregorDeCillia** [comment]
Thank you for the quick merge!

It almost works. In `R/aceAutocomplete.R` you just need to replace

    comps <- list(
      id = inputId,
      codeCompletions = jsonlite::toJSON(codeCompletions, auto_unbox = TRUE)
    )

with

    comps <- list(
      id = session$ns(inputId),
      codeCompletions = jsonlite::toJSON(codeCompletions, auto_unbox = TRUE)
    )

as I did in my PR. Then the `autoComplete` works even with nested modules.

**Comment by vnijs** [comment]
Thanks for checking @GregorDeCillia. The current version on GitHub should work but please do check. FYI I also updated credits in the NEWS.md and README.md files.

**Comment by GregorDeCillia** [comment]
I can confirm that the current version on github does work with my project. Thanks for mentioning me as a contributor.

**Comment by vnijs** [comment]
Thanks @GregorDeCillia. Closing issue
