### ISSUE TITLE
Producing Slides With KnitR

### ISSUE THREAD

**Issue by gfleetwood** [trestletech/shinyAce#58]
[This example](https://github.com/trestletech/shinyAce/tree/master/inst/examples/03-knitr) shows how to use shinyAce and knitR to knit an Rmarkdown document. Can this be extended to kniting slides?

**Comment by vnijs** [comment]
That should be possible if you use Rmarkdown to generate the document rather than knitr. Take a look at the `editR` repo linked below for ideas.

https://github.com/swarm-lab/editR
