### ISSUE TITLE
Update in CRAN?

### ISSUE THREAD

**Issue by elinw** [trestletech/shinyAce#60]
CRAN won't let you use a remote repository, and I need the update with the fix from @laderast ... is there any chance you would do a CRAN update?

**Comment by vnijs** [comment]
FYI @elinw 

On 10/2/18, 2:31 PM, "ligges@..." <ligges@...> wrote:

Dear maintainer,
     
thanks, package shinyAce_0.3.2.tar.gz is on its way to CRAN.
     
Best regards,
CRAN teams' auto-check service

**Comment by vnijs** [comment]
FYI shinyAce 0.3.2 is now available for all platforms on CRAN
