### ISSUE TITLE
Shiny app does not load properly - after 0.4.0

### ISSUE THREAD

**Issue by federicomarini** [trestletech/shinyAce#64]
Hi @vnijs,

I am trying to debug the behavior described in https://github.com/federicomarini/pcaExplorer/issues/6 - which thanks to the help of some other users can be pinpointed to some changes after updating the mighty shinyAce.

I did get the email when you were mentioning the upcoming breaking changes, but I could not identify what triggers the unwanted behavior - in brief: the app does not load many of its components.

Now, following the info in the news, I could not find a clear spot where this gets triggered - I am only using `aceAutocomplete`, `aceEditor`, `getAceModes`, `getAceThemes`, and `updateAceEditor`. These are used in the main app R file, https://github.com/federicomarini/pcaExplorer/blob/master/R/pcaExplorer.R, with the element called `acereport_rmd`.

I hope you can give me some help on this - maybe I am naively missing something?

Thank you in advance for all the help - and of course, for keeping up the develoment!

Federico

**Comment by federicomarini** [comment]
Side note - everything was working as expected with version 0.3.2 of `shinyAce`, I forgot to mention that.

**Comment by vnijs** [comment]
Are you sure shinyAce is the problem? I just installed you app locally and, as far I can see the shinyAce input is working fine.

![image](https://user-images.githubusercontent.com/2998956/62735877-07229d80-b9e1-11e9-998b-f701781e564c.png)

I did see one warning show below:

Warning: Error in loadNamespace: there is no package called 'BiocStyle'

**Comment by federicomarini** [comment]
Hi @vnijs 
Thanks for checking in.

It can be that you did not encounter the problem because it seems to be fixed by the edit I undertook this afternoon.

https://github.com/federicomarini/pcaExplorer/commit/a5a2439750808a7562d710f98529335360d2b16f

Basically, it did not like I was initializing the value via a `readLines` call. This worked in the former versions, so it was a little hard to track down - I could not "see" any mention to this change in the News

**Comment by vnijs** [comment]
Good to hear. See my comment on federicomarini/pcaExplorer@a5a2439 . I'll close for now but feel free to reopen if needed.

**Comment by vnijs** [comment]
FYI shinyAce will accept a vector or list as input for the `value` argument in a future release. See https://github.com/trestletech/shinyAce/commit/abcc4fc0382ecdf251e02b6dc33ef947129e5db3

**Comment by federicomarini** [comment]
Cool, thanks for the pointer!
