### ISSUE TITLE
modes from original ace are not supported

### ISSUE THREAD

**Issue by certara-mtomashevskiy** [trestletech/shinyAce#71]
Hi,

I tried to create new mode using the existed ones but the js files are formatted in a way difficult to understand and to change
so I tried to substitute the mode for R to the original one:
https://github.com/trestletech/shinyAce/blob/master/inst/www/ace/mode-r.js
->
https://github.com/ajaxorg/ace-builds/blob/master/src/mode-r.js

unfortunately it does not work.
is there any instruction showing the process of modes modification/creation as it is shown [here](https://github.com/ajaxorg/ace/wiki/Creating-or-Extending-an-Edit-Mode)?

**Comment by vnijs** [comment]
The js files in the ace/ directory are unchanged and come directly from the folks developing ace editor. These files are minified and if you want to get them in a readable format you would have to "unminify" them, e.g., using the site linked below. If you have a (working) mode you would like to include in shinyAce I'd be happy to consider it, especially if it is for Rmarkdown :)

https://unminify.com/

**Comment by certara-mtomashevskiy** [comment]
thank you Vincent!
I think I figured out what are the differences in js files, so this is not an issue anymore.
