### ISSUE TITLE
new mode: PML

### ISSUE THREAD

**Issue by certara-mtomashevskiy** [trestletech/shinyAce#72]
Hi,

I created a new mode for Phoenix Modelling Language.
[mode-pml.js.txt](https://github.com/trestletech/shinyAce/files/4652763/mode-pml.js.txt)

The help for the language could be found [here].(https://onlinehelp.certara.com/phoenix/8.3/index.html#t=topics%2Fintropml.htm)

Is it possible to add it to shinyAce? Should I create pull request?

**Comment by vnijs** [comment]
A PR would be great @certara-mtomashevskiy. Thanks!
