### ISSUE TITLE
a way to hide the vertical ruler in Ace Editor

### ISSUE THREAD

**Issue by certara-mtomashevskiy** [trestletech/shinyAce#74]
Hi,

is it possible to add the option to hide vertical ruler?
it is described [here](https://stackoverflow.com/questions/14907184/is-there-a-way-to-hide-the-vertical-ruler-in-ace-editor)

**Comment by vnijs** [comment]
This would require an additional argument for `aceEditor` and `updateAceEditor`. Want to create a PR?

**Comment by samssann** [comment]
I hid it with css changes
```
.ace_scroller .ace_content .ace_print-margin-layer .ace_print-margin {
  visibility: hidden !important;
}
```
